name: Redeploy Choreo

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  Redeploy:
    name: Redeploy Choreo

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0
        with:
          fetch-depth: 1

      - name: Renew README.md
        run: |
            DATE=$(date "+%Y/%m/%d %H:%M:%S")
            echo "${DATE}" > README.md
            git checkout --orphan tmp_work
            git branch -d main
            echo "DATE=${DATE}" >> $GITHUB_ENV

      - name: Upload to repository
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: Auto deploy by Github Actions, ${{ env.DATE }}
          branch: main
          push_options: --force
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }} # Custom PAT for actions requiring higher permissions

      - name: Delete old workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          github_token: ${{ secrets.REPO_ACCESS_TOKEN }} # Use the same custom PAT as before
          repository: ${{ github.repository }}
          older-than-seconds: 3600
